### ISSUE TITLE
new issue

### ISSUE THREAD

**Issue by mdc2684** [mdc2684/HH99firstSpringLevelone#1]
.

**Comment by mdc2684** [comment]
BoardService의 48line 
예외처리로 클라이언트에게 메세지를 주고 싶은데 어떤 방법이 있을까요

**Comment by mdc2684** [comment]
저는 테이블(entity) join 없이 과제를 해결했는데요, join으로도 가능 하다고 알게 되었는데, join으로 하는게 더 좋은건지 더 좋다면 그 이유는 무엇일까요

**Comment by paran22** [comment]
- 데이터베이스와 우리가 현재 사용하고 있는 JPA(ORM) 용어는 조금 구분해서 사용하시면 좋을 것 같아요. 데이터베이스에서는 연관된 테이블들을 join해서 사용하는데 JPA에서는 테이블과 매핑되는 엔티티를 만들고, 엔티티 간에 연관관계를 설정합니다. 자세한 내용은 lv3 과제를 하시면서 더 공부하게 될 거에요! 지금은 연관관계가 맺어져 있지 않은 상태이니까 이 상태로 과제 진행하시고, lv3때 연관관계를 설정해보면서 차이에 대해서 같이 더 얘기해보면 좋을 것 같네요.

**Comment by paran22** [comment]
```
    @ResponseBody
    @PostMapping("/login")
    public ResponseEntity<MsgResponseDto> login(@RequestBody LoginRequestDto loginRequestDto, HttpServletResponse response) {  // 만들어준 Token을 넣어주기위해
        userService.login(loginRequestDto, response);
        return ResponseEntity.ok(new MsgResponseDto("로그인완료", HttpStatus.OK.value()));
    }
```

delete api를 구현하실 때 service는 void로 만드시고 controller에서 성공했을 때 ResponseEntity가 리턴되게 구현되어 있는데요.
service 안에 exception을 throw하는 부분이 있어서 아마 에러가 있다면 이 controller에 있는 마지막 return 전에 에러를 던지고 끝날 거에요.
그래서 로직 상에는 크게 문제가 없는 것 같은데, service 메서드 자체는 void라서 아무 값도 리턴하지 않는데 controller에서 성공 메시지를 남겨주고 있어서 관련된 로직이 흩어진 느낌이 듭니다.
controller의 return이 service 로직이 성공적으로 끝났을 때 리턴하는 걸 의도하신 거라면 service 로직 내에서 처리하는게 좋을 것 같아요!

**Comment by mdc2684** [comment]
감사합니다 delete api 수정하였습니다.

그리고 기능들에는 문제없이 잘 되는데 DB를 보면 USER_ID라는 새로운 컬럼이 왜 필요한지 모르겠고, 전부 null로 나오는데 이유를 모르겠습니다.
![111](https://user-images.githubusercontent.com/69786324/233763244-447359d4-8240-4f30-a344-f6c585c9493c.JPG)

이유는 모르겠으나 현시점 해결이 되었습니다;;ㅎㅎ

**Comment by mdc2684** [comment]
BoardService에서 createBoard 코드 질문 있습니다.
51번째줄에서 user정보를 찾아서 user에 user데이터를 담고,
56번째줄  Board board = boardRepository.save(new Board(boardRequestDto, user)); 에 user객체 자체를 넣는데요,
제 생각에는 username만 있으면 되니까 user.username()으로 하는게 더 낫지 않나 생각이 듭니다
그리고 user객체 자체를 넣으면 user의 정보인 비밀번호도 들어가니까 보안상도 위험한게 아닌가 생각이 드는데

어떤걸 해도 상관이 없는건가요?

**Comment by mdc2684** [comment]
현재 정규표현식을 EntityUser에 구현을 해 놓은상태인데요,
회원가입할때 SignupRequestDto에서 구현을 하는게 더 좋은 설계일까요?
개인적으로는 정규표현식 검사를 위해 entitiy까지 가야하는 길이 멀어서라고 생각했는데 정확한 이유는 무엇일까요?

**Comment by paran22** [comment]
현재 코드를 봤을 때, User와 Board를 JPA 연관관계로 매핑해놓으셨기 때문에, Board를 저장할 때 User 정보가 제대로 들어가지 않아서 null이 떴을 것 같아요. 현재 코드에서는 Board를 저장할 때 jwt 토근으로 찾은 user도 함께 저장하고 있어서 문제가 해결되었을 것 같네요.

이거랑 관련해서 왜 username이 아니라 user를 저장해야하는지 질문하셨는데, user를 저장한 이유는 User와 Board가 연관관계를 맺었기 때문이에요. 만약에 처음에 작성하신 코드처럼 연관관계를 맺지 않고 Board에 username만 저장하고 싶다면 그렇게 하셔도 상관은 없습니다.
그렇지만 우리가 연관관계를 사용하는 이유는 단순히 Board라는 username이라는 값을 저장하려는 목적보다는 Board와 연관된 User를(여기서는 작성한 User) 연관관계를 맺어서 엔티티를 관리하려고 하기 때문이에요. 둘이 연관관계를 맺어 놓았기 때문에 관련된 비즈니스 로직을 처리할 때 좀 더 쉽게 코드를 작성할 수도 있고, JPA가 제공하는 여러 편의 기능들(예를 들어 1차 캐시)을 활용할 수 있습니다. 그렇지만 JPA 연관관계도 잘 이해하고 사용을 해야해요! lv3과제를 하면서 본격적으로 연관관계에서 대해 자세히 공부하실 거에요!

**Comment by paran22** [comment]
정규표현식 등을 활용해서 유효성 검사를 자주 하게 될 텐데, 어느 시점에서 유효성 검사를 하는게 효율적일지에 대해서는 유효성 검사가 사용되는 로직의 순서를 전체적으로 체크해보시면서 생각해보면 좋을 것 같아요. 유효성 검사에서 통과하지 않으면 보통 에러를 던지기 때문에 이후 로직은 동작하지 않을 거에요. 만약에 SignupRequestDto에서 검증을 한다면 일단 controller에 dto가 들어온 시점에서 값을 검증할 수 있을거고, entity에서 한다면 entity instance가 생기는 시점에서 검증이 될거에요. 유효성 검사 방법도 사용하신 @Pattern 이외에도 여러가지 방법이 있어서, 다양하게 적용해보시면서 각각의 특징을 살펴보시는 것도 좋을 것 같네요.

**Comment by paran22** [comment]
비밀번호는 말씀하신 것 처럼 암호화하는게 맞고, lv3에서 암호화 적용하실거에요! lv2에서는 간단하게 jwt를 구현해보기위해 생략됬다고 보셔도 될 것 같네요.
